trigger:
  branches:
    include:
      - main

jobs:
  - job: deploy
    displayName: 'Deploy Changed Components to Salesforce'
    pool:
      vmImage: 'ubuntu-latest'  # Use Ubuntu for Bash support

    steps:
      - checkout: self
        displayName: 'Checkout Repository'

      - script: |
          echo "Getting list of changed files..."
          git fetch origin
          OLD_COMMIT=$(git rev-parse HEAD~1)
          NEW_COMMIT=$(git rev-parse HEAD)
          echo "Old Commit: $OLD_COMMIT"
          echo "New Commit: $NEW_COMMIT"

          git diff --name-only $OLD_COMMIT $NEW_COMMIT > changed_files.txt
          echo "Changed files:"
          cat changed_files.txt
        displayName: 'Detect Changed Files'

      - script: |
          echo "Filtering deployable metadata components..."
          mkdir -p changed-metadata
          while IFS= read -r file; do
            if [[ "$file" == force-app/* && -f "$file" ]]; then
              mkdir -p "changed-metadata/$(dirname "$file")"
              cp "$file" "changed-metadata/$file"
            fi
          done < changed_files.txt

          echo "Changed metadata files:"
          find changed-metadata
        displayName: 'Prepare Changed Metadata'

      - script: |
          echo "Authenticating to UAT Org..."
          sfdx auth:web:login --setalias UatOrg --instanceurl https://taruitsolutions-6e-dev-ed.develop.my.salesforce.com
        displayName: 'Authenticate to UAT Org'

      - script: |
          echo "Deploying changed metadata to UAT Org..."
          sf project deploy start --source-dir changed-metadata --target-org UatOrg --ignore-warnings
        displayName: 'Deploy to UAT Org'
