trigger:
  branches:
    include:
      - main

pool:
  name: 'Default'

jobs:
- job: deploy
  displayName: 'Deploy changed components to Salesforce'

  steps:
    # Step 1: Checkout the repository with full history
    - checkout: self
      displayName: 'Checkout repository'
      fetchDepth: 0

    # Step 2: Detect changed files
    - script: |
        echo Getting list of changed files...
        git fetch origin
        for /f %%i in ('git rev-parse HEAD~1') do set OLD_COMMIT=%%i
        for /f %%i in ('git rev-parse HEAD') do set NEW_COMMIT=%%i
        echo Old Commit: %OLD_COMMIT%
        echo New Commit: %NEW_COMMIT%
        git diff --name-only %OLD_COMMIT% %NEW_COMMIT% > changed_files.txt
        echo Changed files:
        type changed_files.txt
      displayName: 'Detect changed files'

    # Step 3: Prepare changed metadata
    - script: |
        echo Filtering metadata components...
        mkdir changed-metadata
        setlocal EnableDelayedExpansion
        for /f "usebackq delims=" %%f in ("changed_files.txt") do (
          echo Checking %%f
          echo %%f | findstr /R "^force-app\\.*" >nul
          if !errorlevel! == 0 (
            if exist "%%f" (
              echo Copying %%f
              mkdir "changed-metadata\%%~dpf" >nul 2>&1
              xcopy /Y /I "%%f" "changed-metadata\%%f"
            )
          )
        )
        echo Listing changed metadata:
        dir changed-metadata /s
      displayName: 'Prepare changed metadata'

    # Step 4: Login to Salesforce using web auth
    - script: |
        echo Logging into Salesforce using web login...
        sf org login web --set-default --alias UatOrg
      displayName: 'Web Login to UatOrg'

    # Step 5: Deploy to Salesforce
    - script: |
        echo Deploying to UatOrg...
        sf project deploy start --source-dir changed-metadata --target-org UatOrg
      displayName: 'Deploy to UatOrg'
