name: Detect Changed Files

on:
  push:
    branches:
      - main

jobs:
  detect-changes:
    runs-on: AVI0124

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Show recent commits
        run: |
          echo "Latest 2 commits:"
          git log -n 2 --oneline

      - name: Detect changed files
        run: |
          echo "Comparing HEAD^ and HEAD..."
          git diff --name-status HEAD^ HEAD > changed_files.txt
          echo "Changed files:"
          cat changed_files.txt
